# -*- coding: utf-8 -*-
"""web crawler - verge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKw3P4QEV7Cm1I5U_Gm7Df2oVYq4tjSy

# Import
"""

from __future__ import annotations

import time
import queue
import threading
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Set
from urllib.parse import urljoin, urlparse, urlunparse
from urllib.request import urlopen, Request

from bs4 import BeautifulSoup

"""# Utils"""

def normalize_url(url: str) -> Optional[str]:
  try:
    parsed = urlparse(url.strip())
    if parsed.scheme not in ("http", "https"):
      return None
    if not parsed.netloc:
      return None

    scheme = parsed.scheme.lower()
    hostname = parsed.hostname.lower()
    path = parsed.path or "/"
    if path !="/" and path.endswith("/"):
      path = path[:-1]

    return urlunparse((scheme, hostname, path, "", parsed.query, ""))
  except Exception:
    return None


def is_allowed_domain(url:str, allowed_domains: Set[str]) -> bool:
  parsed = urlparse(url)
  if parsed.hostname is None:
    return False
  hostname = parsed.hostname.lower()
  for allowed_domain in allowed_domains:
    if hostname == allowed_domain or hostname.endswith("." + allowed_domain):
      return True
  return False


def extract_links(base_url: str, html: str) -> list[str]:
  soup = BeautifulSoup(html, "html.parser")
  links = []

  for tag in soup.find_all("a", href = True):
    href = tag["href"]
    normalized_url = normalize_url(urljoin(base_url, href))
    if normalized_url:
      links.append(normalized_url)

  return links

"""## Support for Verge on a certain date"""

from datetime import datetime, date
from typing import Optional
from bs4 import BeautifulSoup # Ensure BeautifulSoup is imported here too for robustness

def extract_verge_article_date(html_content: str) -> Optional[date]:
    """Extracts the publication date from a Verge article's HTML content."""
    soup = BeautifulSoup(html_content, 'html.parser')

    # Attempt 1: Find <time> tag with the new class (for newer articles)
    time_tag = soup.find('time', class_='c-byline__item c-byline__item--date')
    if time_tag and 'datetime' in time_tag.attrs:
        date_str = time_tag['datetime']
        try:
            return datetime.fromisoformat(date_str).date()
        except ValueError:
            pass # Continue to next attempt if parsing fails

    # Attempt 2: Find <meta property="article:published_time"> (for older articles or robust fallback)
    meta_tag = soup.find('meta', property='article:published_time')
    if meta_tag and 'content' in meta_tag.attrs:
        date_str = meta_tag['content']
        try:
            return datetime.fromisoformat(date_str).date()
        except ValueError:
            pass # Continue if parsing fails

    return None

test_url = "https://www.theverge.com/entertainment/960958/flatbush-zombies-erick-the-architect-interview"

try:
    with urlopen(test_url) as response:
        html_content = response.read().decode('utf-8')
    extracted_date = extract_verge_article_date(html_content)
    print(f"Extracted date for {test_url}: {extracted_date}")
except Exception as e:
    print(f"Error fetching or processing {test_url}: {e}")

"""## Rate Limiter"""

# This cell is now empty as its content has been moved.
class PerHostRateLimiter:
  def __init__(self, min_delay_seconds:float) -> None:
    self.min_delay_seconds = min_delay_seconds
    self.lock = threading.Lock()
    self.next_allowed_time: Dict[str, float] = {}

  def wait(self, hostname:str) ->None:
    while True:
      now = time.monotonic() # Define 'now' before it's used
      with self.lock: # Corrected from self.Lock to self.lock
        next_time = self.next_allowed_time.get(hostname, now)
        if now >= next_time:
          self.next_allowed_time[hostname] = now + self.min_delay_seconds
          return
      time.sleep(max(0, next_time - now)) # Ensure sleep time is not negative

"""# Crawler"""

@dataclass
class CrawlTask:
  url: str
  depth: int
  retry_count: int = 0

@dataclass
class CrawlResult:
  url: str
  depth: int
  new_links: list[str] = field(default_factory=list)
  error: Optional[str] = None
  html_content: Optional[str] = None

class WebCrawler:
  def __init__(
      self,
      start_urls:List[str],
      allowed_domains: List[str],
      num_threads: int = 8,
      max_depth: int = 2,
      min_delay_seconds: float = 0.5,
      max_retry:int = 2,
      request_timeout: float = 10.0,
      user_agent: str = "crawler/1.0",
      max_num: int = 500,
      filter_date: Optional[date] = None
      ) -> None:
    self.start_urls = []
    for url in start_urls:
      n_url = normalize_url(url)
      if n_url:
        self.start_urls.append(n_url)
    if not self.start_urls:
      raise ValueError("no valid start urls")

    if not allowed_domains:
      raise ValueError("no allowed domains")

    self.user_agent = user_agent

    # Canonicalize allowed_domains to include both bare and www-prefixed versions
    canonical_allowed_domains = set()
    for domain in allowed_domains:
      canonical_allowed_domains.add(domain)
      if domain.startswith("www."):
        canonical_allowed_domains.add(domain[4:]) # Add bare domain
      else:
        canonical_allowed_domains.add(f"www.{domain}") # Add www-prefixed domain
    self.allowed_domains = canonical_allowed_domains

    self.max_retry = max_retry
    self.max_depth = max_depth
    self.num_threads = num_threads

    self.rate_limiter = PerHostRateLimiter(min_delay_seconds)
    self.request_timeout = request_timeout

    self.seen_lock = threading.Lock()
    self.seen:Set[str] = set()

    self.results_lock = threading.Lock()
    self.results: List[any] = []

    self.stop_event = threading.Event()

    self.tasks = queue.Queue()
    self.threads: List[threading.Thread] = []
    self.max_num: int = max_num
    self.filter_date = filter_date

  def crawl(self) -> List[any]:
    for url in self.start_urls:
      self._schedule_if_new(url)

    for i in range(self.num_threads):
      new_thread = threading.Thread(
          target = self._worker,
          name = f"crawler-{i}",
          daemon = True,
      )
      new_thread.start()
      self.threads.append(new_thread)

    print("Main thread waiting for tasks to complete...", flush=True)
    self.tasks.join()
    print("All tasks completed.", flush=True)

    self.stop()
    for _ in range(self.num_threads):
      self.tasks.put(None)

    for thread in self.threads:
      thread.join()
    return self.results


  def stop(self) -> None:
    self.stop_event.set()

  def _schedule_if_new(self, url:str, depth:int = 0, retry:int = 0) -> bool:
    with self.seen_lock:
      if len(self.seen)>= self.max_num:
        return False
      if url not in self.seen:
        self.seen.add(url)
        new_task = CrawlTask(url, depth, retry)
        self.tasks.put(new_task)
        return True
    return False

  def _worker(self) -> None:
    print(f"Worker {threading.current_thread().name} starting...", flush=True)
    while not self.stop_event.is_set():
      task = self.tasks.get()
      if task is None: # Poison pill
        print(f"Worker {threading.current_thread().name} received poison pill.", flush=True)
        self.tasks.task_done()
        return
      try:
        self._process_task(task)
      finally:
        self.tasks.task_done()
    print(f"Worker {threading.current_thread().name} stopping", flush=True)


  def _process_task(self, task: CrawlTask) -> None:
    try:
      result = self._fetch(task)
    except Exception as e:
      if task.retry_count < self.max_retry:
        time.sleep(2**task.retry_count)

        new_task = CrawlTask(task.url, task.depth, task.retry_count + 1)
        self.tasks.put(new_task)
        print(f"Retrying: {new_task.url} (Attempt: {new_task.retry_count})", flush=True)
        return
      else:
        result = CrawlResult(task.url, task.depth, new_links =[], error = str(e))
        print(f"Failed after retries: {task.url} (Error: {e})", flush=True)

    # Decide whether to add the result based on filter_date
    if self.filter_date is not None:
        # If a filter date is set, only consider Verge articles for filtering
        if result.html_content and result.url.startswith("https://www.theverge.com/"):
            article_date = extract_verge_article_date(result.html_content)
            print(f"date: {article_date}")
            if article_date and article_date >= self.filter_date:
                print(result.url, result.depth)
                with self.results_lock:
                    self.results.append((result.url, result.depth)) # Add only the URL string
            if article_date and article_date < self.filter_date:
                #print("previous date, stop")
                return
    else:
        # If no filter date is set, add all CrawlResult objects
        with self.results_lock:
            self.results.append(result)

    if result.depth >= self.max_depth:
      return

    for new_link in result.new_links:
      if is_allowed_domain(new_link, self.allowed_domains):
        self._schedule_if_new(new_link, task.depth + 1, 0)
    return


  def _fetch(self, task:CrawlTask) -> CrawlResult:
    url = task.url
    depth = task.depth
    parsed = urlparse(url)
    hostname = parsed.hostname
    self.rate_limiter.wait(hostname)

    headers = {"User-Agent": self.user_agent}
    request = Request(url, headers = headers)
    with urlopen(request, timeout = self.request_timeout) as response:
      body_bytes = response.read()
      content_type = response.headers.get("Content-Type", "").split(";")[0].strip().lower()
      status_code = getattr(response, "status", 200)

    new_links = []
    html_content = None
    if content_type.startswith("text/html") :
      html_content =  body_bytes.decode("utf-8")
      new_links = extract_links(url, html_content)

    return CrawlResult(url, depth, new_links, html_content=html_content)

"""seen lock, results lock
threads, task queue

request timeout

thread.start()

Queue
* task_done()

# Main
"""

# Main
from datetime import date # Ensure date is imported

start_urls = ["https://www.theverge.com/"]
allowed_domains = ["www.theverge.com"]

crawler = WebCrawler(start_urls, allowed_domains, max_num = 3000, filter_date=date.today())
results = crawler.crawl()

output_filename = "crawl_results.txt"
with open(output_filename, "w") as f:
  for url, depth in results:
    f.write(f"URL: {url}, Depth: {depth}\n")

print(f"Crawl results saved to {output_filename}")